export const projectFocusContent = {
  es: {
    allProjects: "Todos",
    projectsPrimaryLabel: "Proyectos",
    projectsPrimaryTitle: "Encuentra rápido la herramienta que necesitas",
    projectsPrimaryCopy:
      "Puedes filtrar las apps por categoría, buscarlas por nombre y localizar rápido la herramienta que necesitas para una tarea concreta.",
    searchPlaceholder: "Buscar por nombre, función o slug",
    searchLabel: "Buscar proyectos",
    categorySummary: "Categorías",
    resultsLabel: "Resultados",
    clearFilter: "Limpiar",
    noResultsTitle: "No hay coincidencias con ese filtro",
    noResultsCopy: "Prueba otra categoría o cambia el texto de búsqueda para volver a mostrar el catálogo completo.",
    storyLabel: "Historia",
    storyTitle: "Por qué existe gallego.top",
    storyLead:
      "La idea nace de una necesidad bastante simple: tener herramientas útiles para el trabajo docente sin depender de flujos más pesados de lo necesario.",
    storyParagraphs: [
      "Muchas de estas apps surgen al preparar clases, revisar documentos, traducir materiales o resolver tareas repetitivas que consumen tiempo real.",
      "El proyecto fue creciendo como un conjunto de utilidades concretas. Primero apareció la necesidad, luego la app. No al revés.",
      "Por eso la web pone ahora el catálogo en primer plano y deja la historia como contexto: lo importante es encontrar rápido qué proyecto resuelve cada problema.",
    ],
    storyPoints: [
      "Problema real de aula o de gestión.",
      "Herramienta ligera para resolverlo desde el navegador.",
      "Catálogo abierto que sigue creciendo con nuevas ideas.",
    ],
    internalOnly: "Apps propias",
    externalAfter: "Proyectos afines",
  },
  gl: {
    allProjects: "Todos",
    projectsPrimaryLabel: "Proxectos",
    projectsPrimaryTitle: "Atopa rápido a ferramenta que precisas",
    projectsPrimaryCopy:
      "Podes filtrar as apps por categoría, buscalas por nome e atopar rápido a ferramenta que precisas para unha tarefa concreta.",
    searchPlaceholder: "Buscar por nome, función ou slug",
    searchLabel: "Buscar proxectos",
    categorySummary: "Categorías",
    resultsLabel: "Resultados",
    clearFilter: "Limpar",
    noResultsTitle: "Non hai coincidencias con ese filtro",
    noResultsCopy: "Proba outra categoría ou cambia o texto de busca para volver mostrar o catálogo completo.",
    storyLabel: "Historia",
    storyTitle: "Por que existe gallego.top",
    storyLead:
      "A idea nace dunha necesidade bastante simple: ter ferramentas útiles para o traballo docente sen depender de fluxos máis pesados do necesario.",
    storyParagraphs: [
      "Moitas destas apps xorden ao preparar clases, revisar documentos, traducir materiais ou resolver tarefas repetitivas que consomen tempo real.",
      "O proxecto foi medrando como un conxunto de utilidades concretas. Primeiro apareceu a necesidade, logo a app. Non ao revés.",
      "Por iso a web pon agora o catálogo en primeiro plano e deixa a historia como contexto: o importante é atopar rápido que proxecto resolve cada problema.",
    ],
    storyPoints: [
      "Problema real de aula ou de xestión.",
      "Ferramenta lixeira para resolvelo dende o navegador.",
      "Catálogo aberto que segue medrando con novas ideas.",
    ],
    internalOnly: "Apps propias",
    externalAfter: "Proxectos afíns",
  },
  ca: {
    allProjects: "Tots",
    projectsPrimaryLabel: "Projectes",
    projectsPrimaryTitle: "Troba ràpid l'eina que necessites",
    projectsPrimaryCopy:
      "Pots filtrar les apps per categoria, cercar-les pel nom i trobar ràpid l'eina que necessites per a una tasca concreta.",
    searchPlaceholder: "Cerca per nom, funció o slug",
    searchLabel: "Cercar projectes",
    categorySummary: "Categories",
    resultsLabel: "Resultats",
    clearFilter: "Netejar",
    noResultsTitle: "No hi ha coincidències amb aquest filtre",
    noResultsCopy: "Prova una altra categoria o canvia el text de cerca per tornar a mostrar tot el catàleg.",
    storyLabel: "Història",
    storyTitle: "Per què existeix gallego.top",
    storyLead:
      "La idea neix d'una necessitat molt simple: tenir eines útils per a la feina docent sense dependre de fluxos més pesats del necessari.",
    storyParagraphs: [
      "Moltes d'aquestes apps sorgeixen en preparar classes, revisar documents, traduir materials o resoldre tasques repetitives que consumeixen temps real.",
      "El projecte va créixer com un conjunt d'utilitats concretes. Primer va aparèixer la necessitat, després l'app. No a l'inrevés.",
      "Per això la web posa ara el catàleg en primer pla i deixa la història com a context: l'important és trobar ràpid quin projecte resol cada problema.",
    ],
    storyPoints: [
      "Problema real d'aula o de gestió.",
      "Eina lleugera per resoldre'l des del navegador.",
      "Catàleg obert que continua creixent amb noves idees.",
    ],
    internalOnly: "Apps pròpies",
    externalAfter: "Projectes afins",
  },
  eu: {
    allProjects: "Guztiak",
    projectsPrimaryLabel: "Proiektuak",
    projectsPrimaryTitle: "Aurkitu azkar behar duzun tresna",
    projectsPrimaryCopy:
      "App-ak kategoriaren arabera iragazi, izenaren arabera bilatu eta zeregin zehatz baterako behar duzun tresna azkar aurki dezakezu.",
    searchPlaceholder: "Bilatu izenaren, funtzioaren edo slugaren arabera",
    searchLabel: "Bilatu proiektuak",
    categorySummary: "Kategoriak",
    resultsLabel: "Emaitzak",
    clearFilter: "Garbitu",
    noResultsTitle: "Ez dago iragazki horrekin bat datorrenik",
    noResultsCopy: "Saiatu beste kategoria batekin edo aldatu bilaketa testua katalogo osoa berriro ikusteko.",
    storyLabel: "Historia",
    storyTitle: "Zergatik existitzen da gallego.top",
    storyLead:
      "Ideia behar sinple batetik sortu zen: irakasleen lanerako tresna erabilgarriak edukitzea, behar baino astunagoak diren fluxuen mende egon gabe.",
    storyParagraphs: [
      "App hauetako asko klaseak prestatzean, dokumentuak berrikustean, materialak itzultzean edo benetako denbora jaten duten zeregin errepikakorrak ebaztean sortu dira.",
      "Proiektua utilitate zehatzen multzo gisa hazi da. Lehenik beharra agertu zen, gero app-a. Ez alderantziz.",
      "Horregatik webguneak katalogoa lehen planoan jartzen du eta historia testuinguru gisa uzten du: garrantzitsuena arazo bakoitza zein proiektuk konpontzen duen azkar aurkitzea da.",
    ],
    storyPoints: [
      "Ikasgelako edo kudeaketako benetako arazoa.",
      "Nabigatzailetik konpontzeko tresna arina.",
      "Ideia berriekin hazten jarraitzen duen katalogo irekia.",
    ],
    internalOnly: "Norberaren app-ak",
    externalAfter: "Antzeko proiektuak",
  },
  en: {
    allProjects: "All",
    projectsPrimaryLabel: "Projects",
    projectsPrimaryTitle: "Find the right tool faster",
    projectsPrimaryCopy:
      "You can filter apps by category, search by name, and quickly find the tool you need for a specific teaching task.",
    searchPlaceholder: "Search by name, use case or slug",
    searchLabel: "Search projects",
    categorySummary: "Categories",
    resultsLabel: "Results",
    clearFilter: "Clear",
    noResultsTitle: "No projects match that filter",
    noResultsCopy: "Try another category or adjust the search text to bring the full catalogue back.",
    storyLabel: "Story",
    storyTitle: "Why gallego.top exists",
    storyLead:
      "The project starts from a simple need: useful teaching tools that do real work without forcing heavier workflows than necessary.",
    storyParagraphs: [
      "Many of these apps were born while preparing lessons, reviewing documents, translating materials or solving repetitive tasks that consume real time.",
      "The catalogue grew as a set of concrete utilities. First came the need, then the app. Not the other way around.",
      "That is why the site now puts the projects first and leaves the story as supporting context: the key is to find quickly which tool solves which problem.",
    ],
    storyPoints: [
      "A real classroom or coordination problem.",
      "A lightweight browser tool to solve it.",
      "An open catalogue that keeps growing with new ideas.",
    ],
    internalOnly: "Own apps",
    externalAfter: "Related projects",
  },
  fr: {
    allProjects: "Tous",
    projectsPrimaryLabel: "Projets",
    projectsPrimaryTitle: "Trouver plus vite le bon outil",
    projectsPrimaryCopy:
      "Vous pouvez filtrer les apps par catégorie, les chercher par nom et trouver rapidement l'outil adapté à une tâche précise.",
    searchPlaceholder: "Rechercher par nom, usage ou slug",
    searchLabel: "Rechercher des projets",
    categorySummary: "Catégories",
    resultsLabel: "Résultats",
    clearFilter: "Effacer",
    noResultsTitle: "Aucun projet ne correspond à ce filtre",
    noResultsCopy: "Essayez une autre catégorie ou modifiez la recherche pour réafficher tout le catalogue.",
    storyLabel: "Histoire",
    storyTitle: "Pourquoi gallego.top existe",
    storyLead:
      "Le projet part d'un besoin simple : disposer d'outils pédagogiques utiles sans dépendre de flux plus lourds que nécessaire.",
    storyParagraphs: [
      "Beaucoup de ces apps sont nées en préparant des cours, en relisant des documents, en traduisant des supports ou en résolvant des tâches répétitives qui prennent un vrai temps.",
      "Le catalogue a grandi comme un ensemble d'utilitaires concrets. D'abord le besoin, ensuite l'app. Pas l'inverse.",
      "C'est pourquoi le site met désormais les projets au premier plan et garde l'histoire comme contexte : l'essentiel est d'identifier vite quel outil répond à quel problème.",
    ],
    storyPoints: [
      "Un vrai problème de classe ou de coordination.",
      "Un outil léger dans le navigateur pour le résoudre.",
      "Un catalogue ouvert qui continue à grandir.",
    ],
    internalOnly: "Apps propres",
    externalAfter: "Projets proches",
  },
  de: {
    allProjects: "Alle",
    projectsPrimaryLabel: "Projekte",
    projectsPrimaryTitle: "Das passende Tool schneller finden",
    projectsPrimaryCopy:
      "Du kannst die Apps nach Kategorie filtern, nach Namen suchen und schnell das passende Werkzeug für eine konkrete Aufgabe finden.",
    searchPlaceholder: "Nach Name, Anwendungsfall oder Slug suchen",
    searchLabel: "Projekte suchen",
    categorySummary: "Kategorien",
    resultsLabel: "Ergebnisse",
    clearFilter: "Zurücksetzen",
    noResultsTitle: "Keine Projekte passen zu diesem Filter",
    noResultsCopy: "Versuche eine andere Kategorie oder ändere den Suchtext, um wieder den ganzen Katalog zu sehen.",
    storyLabel: "Geschichte",
    storyTitle: "Warum gallego.top existiert",
    storyLead:
      "Das Projekt beginnt mit einem einfachen Bedarf: nützliche Unterrichtstools, die reale Arbeit leisten, ohne unnötig schwere Abläufe zu erzwingen.",
    storyParagraphs: [
      "Viele dieser Apps entstanden beim Vorbereiten von Unterricht, Prüfen von Dokumenten, Übersetzen von Materialien oder Lösen wiederkehrender Aufgaben, die echte Zeit kosten.",
      "Der Katalog ist als Sammlung konkreter Werkzeuge gewachsen. Zuerst kam der Bedarf, dann die App. Nicht umgekehrt.",
      "Deshalb stellt die Website jetzt die Projekte in den Vordergrund und lässt die Geschichte als Kontext stehen: Wichtig ist, schnell zu erkennen, welches Tool welches Problem löst.",
    ],
    storyPoints: [
      "Ein reales Problem aus Unterricht oder Koordination.",
      "Ein leichtes Browser-Tool zur Lösung.",
      "Ein offener Katalog, der weiter wächst.",
    ],
    internalOnly: "Eigene Apps",
    externalAfter: "Verwandte Projekte",
  },
};
